---
title: "Mini-Project 01"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

# Data Visualization Mini Project 1

# Establishing Libraries
```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
library(tidyverse)
```

# Loading the CSV
```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
raw_data <- "https://raw.githubusercontent.com/reisanar/datasets/master/all_billboard_summer_hits.csv"
billboard_data <- read_csv(raw_data)
str(billboard_data)
```

# Plot 1 - Energy and Danceability Over Time
```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
ggplot(billboard_data, aes(x = year)) +
  geom_smooth(aes(y = danceability, color = "Danceability"), se = FALSE) + #used se=FALSE to remove the shading from the lines for better clarity
  geom_smooth(aes(y = energy, color = "Energy"), se = FALSE) +
  labs(title = "Danceability & Energy Trends in Billboard Summer Hits",
       x = "Decade of Song Chart Release",
       y = "Received Score",
       color = "Metric") +
  scale_color_manual(values = c("Danceability" = "black", "Energy" = "red")) +
  scale_x_continuous(limits = c(1960, 2010), breaks = seq(1960, 2010, by = 10), expand = c(0, 0)) + #Looked up syntax for moving origin to 1960. Used this syntax                                                                                                      regularly through the future plots
  theme_classic()
ggsave("Fig1_MiniProject1.png")
```

# Plot 2 - Loudness Distributions Across Each Decade

```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
billboard_data <- billboard_data %>%
mutate(year = as.numeric(year),
decade = factor(floor(year / 10) * 10))  # Looked up floor function to find way to where I can categorize each year into a decade

ggplot(billboard_data, aes(x = decade, y = loudness)) + 
  geom_violin(aes(fill = decade)) + 
  geom_smooth(aes(color = "Linear Trendline", group = 1), method = "lm", se = FALSE, size = 1) + 
  scale_color_manual(name = "Legend", values = c("Linear Trendline" = "blue")) + #Looked up how to remove the years from side legend while keeping trendline
  guides(fill = "none") +  
  labs(
    title = "Loudness Trends in Billboard Summer Hits by Decade",
    x = "Decade",
    y = "Loudness (dB)"
    ) +
  theme_bw()

ggsave("Fig2_MiniProject1.png")
```

# Plot 3 - Comparing Song Characteristics from Past & Present

```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
filtered_data <- billboard_data %>%
  filter(year %in% c(1960, 2010)) %>%
  group_by(year) %>%
  summarise(acousticness = mean(acousticness),
            speechiness = mean(speechiness),
            liveness = mean(liveness),
            valence = mean(valence)) %>%
  pivot_longer(cols = -year, names_to = "Feature", values_to = "Value")

ggplot(filtered_data, aes(x = Value, y = Feature, fill = factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_continuous(limits = c(0, 1), expand=c(0,0)) + 
  labs(title = "Song Characteristics of Past & Present",
       x = "Achieved Score between 0-1",
       y = "Metric",
       fill = "Year") +
  theme_classic()

ggsave("Fig3_MiniProject1.png")
```

# Plot 4 - Song Durations Over Time

```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
ggplot(billboard_data, aes(x = factor(floor(year / 10) * 10), #Again used floor to separate decades
                           fill = cut(duration_ms, breaks = c(0, 150000, 180000, 210000, 240000, Inf), #converting milliseconds to minute ranges
                                      labels = c("<2:30", "2:30-3", "3-3:30", "3:30-4", "4+")))) +
  geom_bar(position = "fill") +
  labs(title = "How Song Durations Changed Across Billboard Charts Over Time",
       x = "Decade",
       y = "Proportional Value",
       fill = "Duration Range") +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_continuous(expand = c(0, 0)) +
  theme_classic()

ggsave("Fig4_MiniProject1.png")
```
# Data Summary - Artist Total Songs in Descending Order
```{r, echo = FALSE, out.width="80%", fig.align='center', message=FALSE, warning=FALSE}
artist_list <- billboard_data %>%
  group_by(artist_name) %>%
  summarise(total_songs = n()) %>%
  arrange(desc(total_songs))
artist_list
```